set proj_name=DxlMaster
set proj_src_files=Dynamixel.cpp DynamixelDevice.cpp DynamixelInterface.cpp DynamixelInterfaceArduinoImpl.cpp
set proj_public_files=DxlMaster.h Dynamixel.h DynamixelConsole.h DynamixelDevice.h DynamixelInterface.h DynamixelInterfaceArduinoImpl.h DynamixelMotor.h DynamixelConsole.cpp DynamixelMotor.cpp